name: "my_first_pipeline"
description: "Самый простой пример ETL пайплайна"
version: "1.0.0"

schedule:
  enabled: false

default_resilience:
  max_attempts: 2
  initial_delay: 1.0
  retry_policy: "exponential_backoff"

stages:

  extract_data:
    stage: extract
    component: http_extract
    component_config:
      url: "https://adm-branch-feedback-classification.dns-shop.ru/negative/predict?text=dsadasda"
      method: "GET"
      response_format: "json"
      timeout: 30

  transform_data:
    stage: transform
    component: json_transform
    depends_on: [extract_data]
    component_config:
      column_operations:
        "full_name": "name + ' (' + username + ')'"
        "domain": "email.split('@')[1] if '@' in email else 'unknown'"

      filter_conditions:
        - "website.is_not_null()"

      sort_columns: ["name"]
      sort_descending: false

required_env_vars: []

max_parallel_stages: 2
default_timeout: 1
